services:
  - type: web
    name: text-editor-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    branches:
      only:
        - main
