services:
  - type: web
    name: text-editor-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: "3000"
    regions:
      - oregon
    healthCheckPath: /
