services:
  - type: web
    name: text-editor-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    regions:
      - oregon
    healthCheckPath: /
