services:
  - type: web
    name: text-editor-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    dockerfilePath: ./Dockerfile
    autoDeploy: true